# ESP32-S3
substitutions:
  name: co2monnz
  display_rotation: "180"
  log_level: DEBUG
  mqtt_host: mqtt-dev.co2mon.nz
  mqtt_env: co2monitor-dev

packages:
  base: !include common/base.yaml

esp32:
  board:  co2monnz-v1
  variant: ESP32S3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y

i2c:
  scl: GPIO21
  sda: GPIO14
  frequency: 100kHz

sensor:
  - platform: scd4x
    id: scd40
    update_interval: "15s"
    co2:
      name: "CO2"
      id: co2
      on_value:
        - lambda: id(lcd_leds)->set_co2(x);
    temperature:
      name: "SCD40 Temperature"
      id: scd40_temperature
    humidity:
      name: "SCD40 Humidity"
      id: scd40_humidity
      on_value:
        - lambda: id(lcd_leds)->set_humidity(x);
  - platform: sht3xd
    id: sht30
    update_interval: "15s"
    temperature:
      name: "Temperature"
      id: temperature
      on_value:
        - lambda: id(lcd_leds)->set_temperature(x);
    humidity:
      name: "Humidity"
      id: humidity
      on_value:
        - lambda: id(lcd_leds)->set_humidity(x);
