# ESP32-S3
substitutions:
  name: co2monnz
  display_rotation: "180"
  log_level: DEBUG
  mqtt_host: mqtt-dev.co2mon.nz
  mqtt_env: co2monitor-dev

packages:
  base: !include common/base.yaml

esp32:
  board:  co2monnz-v1
  variant: ESP32S3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y

i2c:
  scl: GPIO21
  sda: GPIO14
  frequency: 100kHz
