# ESP32
substitutions:
  name: co2monitor
  display_rotation: "0"
  log_level: DEBUG
  mqtt_host: mqtt-dev.co2mon.nz
  mqtt_env: co2monitor-dev

packages:
  base: !include common/base.yaml

esp32:
  board:  esp32doit-devkit-v1
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y

i2c:
  scl: GPIO22
  sda: GPIO21
  frequency: 100kHz